import NavbarActions from "@/components/navbar/navbar-actions";
import "@/styles/globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  UserButton,
} from "@clerk/nextjs";
import { auth } from "@clerk/nextjs/server";

import { type Metadata } from "next";
import { Geist } from "next/font/google";

export const metadata: Metadata = {
  title: "Next.js App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const { userId } = await auth();

  return (
    <html lang="en" className={geist.variable}>
      <body className="h-screen w-screen overflow-hidden bg-[#fafaf9] font-sans antialiased">
        <ClerkProvider>
          <div className="flex h-full flex-col">
            <header className="flex h-16 items-center justify-end gap-4 border-b px-4">
              {!userId ? (
                <>
                  <SignInButton mode="modal">
                    <button className="cursor-pointer text-sm font-medium text-stone-600 hover:text-stone-900">
                      Sign In
                    </button>
                  </SignInButton>

                  <SignUpButton mode="modal">
                    <button className="rounded-sm bg-blue-500 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-blue-600">
                      Sign Up
                    </button>
                  </SignUpButton>
                </>
              ) : (
                <div className="">
                  <NavbarActions userId={userId}/>
                </div>
              )}
            </header>

            <main className="min-h-0 flex-1 overflow-y-auto">{children}</main>
          </div>
        </ClerkProvider>
      </body>
    </html>
  );
}
